#!/bin/bash
#
# chkconfig: 2345 96 15
# description: Starts and stops the @service.name@ service
# 
### BEGIN INIT INFO
# Provides:          continuuity-@service.name@
# Short-Description: Continuuity @service.name@
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:
# Should-Stop:
### END INIT INFO


# drop permissions to continuuity user and run service script

if [[ $UID -eq 0 ]]; then
    su continuuity -c "cd /opt/continuuity/@package.name@/bin; exec ./svc-@service.name@ $*"
else
    cd /opt/continuuity/@package.name@/bin; exec ./svc-@service.name@ $*
fi

