#!/bin/bash
#
# chkconfig: 2345 96 15
# description: Starts and stops the @servicename@ service
# 
### BEGIN INIT INFO
# Provides:          continuuity-@servicename@
# Short-Description: Continuuity @servicename@
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:
# Should-Stop:
### END INIT INFO


# drop permissions to continuuity user and run service script

if [[ $UID -eq 0 ]]; then
    su continuuity -c "cd /opt/continuuity/@packagename@/bin; exec ./svc-@servicename@ $*"
else
    cd /opt/continuuity/@packagename@/bin; exec ./svc-@servicename@ $*
fi

