# Copyright © 2020 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-q', '-m', 'rsync', '-r', '${_GCS_CACHE_PATH}', '/m2_cache']
  volumes:
  - path: '/m2_cache'
    name: 'm2_cache'
- name: 'maven:3-jdk-8'
  entrypoint: 'bash'
  args: ['./cloudbuild.sh']
  env:
  - 'MAVEN_CACHE_DIR=/m2_cache'
  - 'MAVEN_OPTS=-Xmx3000m -Dmaven.repo.local=/m2_cache'
  volumes:
  - path: '/m2_cache'
    name: 'm2_cache'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-q', '-m', 'rsync', '-r', '/m2_cache', '${_GCS_CACHE_PATH}']
  volumes:
  - path: '/m2_cache'
    name: 'm2_cache'
options:
  machineType: 'N1_HIGHCPU_32'
timeout: 3h
