#!/usr/bin/env bash
# Copyright (c) 2012 Continuuity Inc. All rights reserved.

SDK_PACKAGE_NAME=continuuity-sdk

ROOT=`dirname "${BASH_SOURCE-$0}"`
ROOT=`cd "$bin"; pwd`
script=`basename $0`
MY_PID=$$
TEMP_DIR=/tmp/${MY_PID}

# Run the uber maven build to extract everything needed to build the SDK.
mvn package site -P dist,javadocs,release,examples -DskipTests -pl singlenode -am
if [[ $? -ne 0 ]]; then
  echo "Build failed. Fix the build before proceeding"
  exit 1
fi

VERSION=`cat $ROOT/singlenode/target/stage-packaging/opt/continuuity/singlenode/VERSION`
echo $VERSION > $WORKING_DIR/VERSION
WORKING_DIR=$TEMP_DIR/$SDK_PACKAGE_NAME-$VERSION
SDK_PACKAGE=${SDK_PACKAGE_NAME}-${VERSION}
SDK_ZIP_PACKAGE=${SDK_PACKAGE}.zip

# Cleanup trap
cleanup() {
  rm -f $WORKING_DIR
  exit $?
}
trap cleanup SIGINT EXIT

# Remove the directory. Highly un-likely that this will exist.
rm -rf $WORKING_DIR

# Create the subdirectories required for the SDK.
mkdir -p $WORKING_DIR $WORKING_DIR/javadocs $WORKING_DIR/lib \
         $WORKING_DIR/conf $WORKING_DIR/libexec $WORKING_DIR/bin \
         $WORKING_DIR/data $WORKING_DIR/web-app $WORKING_DIR/lib/native \
         $WORKING_DIR/examples

cp    $ROOT/continuuity-api/target/*.jar $WORKING_DIR
cp -r $ROOT/continuuity-api/target/site/apidocs/* $WORKING_DIR/javadocs
cp -r $ROOT/singlenode/target/stage-packaging/opt/continuuity/singlenode/lib/* $WORKING_DIR/lib
cp -r $ROOT/singlenode/src/dist/* $WORKING_DIR
cp -r $ROOT/singlenode/libexec/bin/* $WORKING_DIR/libexec
cp -r $ROOT/singlenode/src/main/resources/* $WORKING_DIR/conf

# Copying the selected files to bin.
cp -r $ROOT/data-fabric/bin/tx-debugger* $WORKING_DIR/bin
cp -r $ROOT/gateway/bin/stream-client $WORKING_DIR/bin
cp -r $ROOT/gateway/bin/meta-client $WORKING_DIR/bin
cp -r $ROOT/gateway/bin/data-client $WORKING_DIR/bin
cp -r $ROOT/singlenode/bin/* $WORKING_DIR/bin
cp -r $ROOT/singlenode/bin/* $WORKING_DIR/bin

# Copying web-app
cp -r $ROOT/web-app/target/local $WORKING_DIR/web-app/

# Windows support
cp $ROOT/continuuity-test/src/main/resources/hadoop.dll $WORKING_DIR/lib/native
cp $ROOT/continuuity-test/src/main/resources/*.exe $WORKING_DIR/bin

# Copying examples
rsync -av --exclude='target' --exclude='build.gradle' $ROOT/examples $WORKING_DIR/examples
find examples -name "*.jar" | egrep -v 'sources|javadoc|original' | rsync -av --files-from=-  . $WORKING_DIR/

# Now build the ZIP
pushd $TEMP_DIR
zip -b /tmp -r $SDK_PACKAGE_ZIP $SDK_PACKAGE
popd

echo "$SDK_PACKAGE_ZIP created."
