#!/bin/bash

#COMMON  post install script for <%= project %>
set -e

package_name="<%= project %>"
version="<%= @version %>"

case "$1" in
  install|upgrade)
    getent group continuuity >/dev/null || groupadd -r continuuity
    getent passwd continuuity >/dev/null || /usr/sbin/useradd --comment "Continuuity User" --shell /bin/bash -M -r -g continuuity --home /var/run/continuuity continuuity
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
esac

