#!/bin/bash
#
# Copyright © 2014-2016 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

#
# chkconfig: 2345 96 15
# description: Starts and stops the @service.name@ service
# 
### BEGIN INIT INFO
# Provides:          cdap-@service.name@
# Short-Description: Cask CDAP @service.name@
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:
# Should-Stop:
### END INIT INFO

SVC_COMMAND="/opt/cdap/@package.name@/bin/svc-@service.name@ $*"

# source configuration, if it exists
if [[ -r /etc/default/cdap-@service.name@ ]]; then
  . /etc/default/cdap-@service.name@
fi

# source cdap-env.sh, if it exists
CDAP_CONF_DIR=${CDAP_CONF_DIR:-/etc/cdap/conf}
if [[ -r ${CDAP_CONF_DIR}/cdap-env.sh ]]; then
  . "${CDAP_CONF_DIR}"/cdap-env.sh
fi

CDAP_USER=${CDAP_USER:-cdap}

# drop permissions to cdap user and run service script

if [[ ${UID} -eq 0 ]]; then
    su ${CDAP_USER} -c "${SVC_COMMAND}"
elif [[ ${USER} == ${CDAP_USER} ]]; then
    ${SVC_COMMAND}
else
    echo "ERROR: Must run this script as root or ${CDAP_USER}!"
    exit 1
fi
