#!/bin/bash

# pre remove script for <%= project %>
set -e

package_name="<%= project %>"
version="<%= @version %>"

case "$1" in
    remove)
      if [ -d /opt/continuuity/$package_name/conf ] ; then
        find /opt/continuuity/$package_name/conf -name '*-env.sh' || xargs -n1 basename | sed 's/-env.sh//' | while read svcname; do
          for svcname in `ls /opt/continuuity/$package_name/conf/*-env.sh | xargs -n1 basename | sed 's/-env.sh//'` ; do
            # stop each service
            if [ -x "/etc/init.d/continuuity-$svcname" ]; then
              invoke-rc.d continuuity-$svcname stop || :
            fi
            if [ -h "/opt/continuuity/$package_name/bin/svc-$svcname" ]; then
              unlink /opt/continuuity/$package_name/bin/svc-$svcname > /dev/null 2>&1 ||:
            fi
            rm -f /opt/continuuity/$package_name/version ||:
          done
        done
      fi
    ;;

    upgrade|deconfigure)
      if [ -d /opt/continuuity/$package_name/conf ] ; then
        find /opt/continuuity/$package_name/conf -name '*-env.sh' || xargs -n1 basename | sed 's/-env.sh//' | while read svcname; do
          for svcname in `ls /opt/continuuity/$package_name/conf/*-env.sh | xargs -n1 basename | sed 's/-env.sh//'` ; do
            if [ -h "/opt/continuuity/$package_name/bin/svc-$svcname" ]; then
              unlink /opt/continuuity/$package_name/bin/svc-$svcname > /dev/null 2>&1 ||:
            fi
            rm -f /opt/continuuity/$package_name/version ||:
            # services will be condrestarted on new package postinstall
          done
        done
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
