#!/bin/bash
#
# chkconfig: 2345 96 15 
# description: Starts and stops the ${project.artifactId}
# processname: java
#
### BEGIN INIT INFO
# Provides:          continuuity-${project.artifactId}
# Short-Description: Continuuity ${project.artifactId}
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:
# Should-Stop:
### END INIT INFO


# drop permissions to continuuity user and run service script

if [[ $UID -eq 0 ]]; then
    su continuuity -c "cd /opt/continuuity/${project.artifactId}/bin; exec ./svc-${project.artifactId} $*"
else
    cd /opt/continuuity/${project.artifactId}/bin; exec ./svc-${project.artifactId} $*
fi

