name: Clear Maven Cache

on:
  workflow_dispatch:  # Should be triggered manually

jobs:
  cleanup:
    runs-on: k8s-runner-build 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Delete Maven Cache
        run: |
          echo "Cleaning Maven cache..."
          rm -rf ~/.m2/repository/*
          echo "Maven cache cleaned."
